# Objective
Company wants to predict whether the employee will leave the organisation or not (Attrition)

# Import the Libraries and Dataset.!

In [1]:
import pandas as pd
import numpy as np

In [2]:
employee = pd.read_csv(r"C:\Users\ganes\Downloads\employee (1).csv")

In [3]:
employee.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

# Data Pre-Processing 

# Step 1 : Univariate Analysis

In [4]:
employee.describe()

Age    DailyRate  DistanceFromHome    Education  EmployeeCount  \
count  1470.000000  1470.000000       1470.000000  1470.000000         1470.0   
mean     36.923810   802.485714          9.192517     2.912925            1.0   
std       9.135373   403.509100          8.106864     1.024165            0.0   
min      18.000000   102.000000          1.000000     1.000000            1.0   
25%      30.000000   465.000000          2.000000     2.000000            1.0   
50%      36.000000   802.000000          7.000000     3.000000            1.0   
75%      43.000000  1157.000000         14.000000     4.000000            1.0   
max      60.000000  1499.000000         29.000000     5.000000            1.0   

       EmployeeNumber  EnvironmentSatisfaction   HourlyRate  JobInvolvement  \
count     1470.000000              1470.000000  1470.000000     1470.000000   
mean      1024.865306                 2.721769    65.891156        2.729932   
std        602.024335                 1.093082    20.329428        0.711561   
min          1.000000                 1.000000    30.000000        1.000000   
25%        491.250000                 2.000000    48.000000        2.000000   
50%       1020.500000                 3.000000    66.000000        3.000000   
75%       1555.750000                 4.000000    83.750000        3.000000   
max       2068.000000                 4.000000   100.000000        4.000000   

          JobLevel  ...  RelationshipSatisfaction  StandardHours  \
count  1470.000000  ...               1470.000000         1470.0   
mean      2.063946  ...                  2.712245           80.0   
std       1.106940  ...                  1.081209            0.0   
min       1.000000  ...                  1.000000           80.0   
25%       1.000000  ...                  2.000000           80.0   
50%       2.000000  ...                  3.000000           80.0   
75%       3.000000  ...                  4.000000           80.0   
max       5.000000  ...                  4.000000           80.0   

       StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
count       1470.000000        1470.000000            1470.000000   
mean           0.793878          11.279592               2.799320   
std            0.852077           7.780782               1.289271   
min            0.000000           0.000000               0.000000   
25%            0.000000           6.000000               2.000000   
50%            1.000000          10.000000               3.000000   
75%            1.000000          15.000000               3.000000   
max            3.000000          40.000000               6.000000   

       WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
count      1470.000000     1470.000000         1470.000000   
mean          2.761224        7.008163            4.229252   
std           0.706476        6.126525            3.623137   
min           1.000000        0.000000            0.000000   
25%           2.000000        3.000000            2.000000   
50%           3.000000        5.000000            3.000000   
75%           3.000000        9.000000            7.000000   
max           4.000000       40.000000           18.000000   

       YearsSinceLastPromotion  YearsWithCurrManager  
count              1470.000000           1470.000000  
mean                  2.187755              4.123129  
std                   3.222430              3.568136  
min                   0.000000              0.000000  
25%                   0.000000              2.000000  
50%                   1.000000              3.000000  
75%                   3.000000              7.000000  
max                  15.000000             17.000000  

[8 rows x 26 columns]

In [5]:
print(employee.EmployeeCount.unique())
print(employee.EmployeeNumber.unique())
print(employee.Over18.unique())
print(employee.StandardHours.unique())

[1]
[   1    2    4 ... 2064 2065 2068]
['Y']
[80]


# Removing Irrelavent Variable

In [6]:
employee = employee.drop(['EmployeeCount','EmployeeNumber','Over18','StandardHours'],axis =1)
employee.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement',
       'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager'],
      dtype='object')

# Checking Missing Value.

In [7]:
# Do we have NA's in data
employee.isna().sum()      # .as means convert, .is means check. 
# isna means Checking 'na' i.e. missing values

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

# Taking subset data of number.

In [8]:
# employee Numeric columns
employee_num = employee[employee.select_dtypes(include =[np.number]).columns.tolist()]

# Taking subset data of category.

In [9]:
employee_dummies = employee[employee.select_dtypes(exclude=[np.number]).columns.tolist()]

# Converting Quality Variable to Number

In [10]:
from sklearn.preprocessing import LabelEncoder


In [11]:
employee_dummies = employee_dummies.apply(LabelEncoder().fit_transform) # Label in Ascending Order!

# Combine the Dataset 

In [12]:
employee_combined =pd.concat([employee_num,employee_dummies],axis= 1)

# Data Partition

In [13]:
# dividing the data into Training and the Test Data.
from sklearn.model_selection import train_test_split

In [14]:
train_x = employee_combined.drop(['Attrition'],axis =1)
train_y = employee_combined['Attrition']

In [15]:
# train test split
X_train,X_test,y_train,y_test =train_test_split(train_x,train_y,test_size =0.3,random_state =231)

# Model Buliding of Dicision Tree

In [16]:
# Import tree classifier model
from sklearn import tree
dt = tree.DecisionTreeClassifier()

# train the model using the traing set
dt.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

# PLotting the tree

In [17]:
import graphviz
from sklearn.externals.six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus
import pydot

C:\Users\ganes\Anaconda3\lib\site-packages\sklearn\externals\six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


In [18]:
df = pd.concat([y_train,X_train],axis = 1)

In [19]:
features =list(df.columns[1:])
features

['Age',
 'DailyRate',
 'DistanceFromHome',
 'Education',
 'EnvironmentSatisfaction',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobSatisfaction',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'OverTime']

In [20]:
''''dot_data = StringIO()
export_graphviz(dt, out_file = dot_data, filled = True, feature_names=features, rounded=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())'''

"'dot_data = StringIO()\nexport_graphviz(dt, out_file = dot_data, filled = True, feature_names=features, rounded=True)\ngraph = pydotplus.graph_from_dot_data(dot_data.getvalue())\nImage(graph.create_png())"

# Step 6: Predictions on Train Dataset

In [21]:
y_predict = dt.predict(X_train)

In [22]:
train = pd.concat([X_train,y_train],axis= 1)

In [23]:
train['Predicted'] = y_predict

# Step 7: Model Performance Matrix

In [24]:
from sklearn.metrics import confusion_matrix
confusion_matrix =confusion_matrix(train['Attrition'],train['Predicted'])
print(confusion_matrix)

[[862   0]
 [  0 167]]


In [25]:
Accuracy_Train=((862+0)/(862+0+0+167)*100)
print(Accuracy_Train)

83.77065111758989


# Step 8: Predictions on Test Dataset

In [26]:
y_prediction = dt.predict(X_test)

In [27]:
test = pd.concat([X_test,y_test],axis =1)

In [28]:
test['Predicted'] = y_prediction

# Step 9: Model Performance Metrics on Test Data

In [29]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test['Attrition'],test['Predicted'])
print(confusion_matrix)

[[321  50]
 [ 42  28]]


In [30]:
Accuracy_test = ((362+50)/(362+50+46+24)*100)
Accuracy_test

85.47717842323651

# Model Improvement by Pruning Method

In [31]:
# Import Classifier Model
from sklearn import tree
dt =tree.DecisionTreeClassifier(criterion= 'gini',min_samples_leaf=50,min_samples_split=100,max_depth=3)

# Train the Model
dt.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=50, min_samples_split=100,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [32]:
from sklearn.metrics import classification_report
print(classification_report(y_test,test['Predicted']))

              precision    recall  f1-score   support

           0       0.88      0.87      0.87       371
           1       0.36      0.40      0.38        70

    accuracy                           0.79       441
   macro avg       0.62      0.63      0.63       441
weighted avg       0.80      0.79      0.80       441

